### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by GDYendell** [epics-containers/pvi#118]

**Comment by coretl** [comment]
Suggest that if we had something like in `NDFile`:
```yaml
  - type: SignalRW
    name: FileFormat
    write_pv: $(P)$(R)FileFormat
    write_widget:
      type: ComboBox
    read_pv: $(P)$(R)FileFormat_RBV
    read_widget:
      type: TextRead
```
Then we could mark it as not to appear on the screen by changing the YAML to:
```yaml
type: IgnoredSignal
name: FileFormat
```
And we could do that either in `NDFile` to mean that it never appeared on any screen, or in `NDFileHDF` if the includer pvi file decided it didn't want a signal from the included pvi file.
