### ISSUE TITLE
Make `ActionButtons(WriteWidget)`

### ISSUE THREAD

**Issue by coretl** [epics-containers/pvi#27]
At the moment we model areaDetector `acquire` as a `SignalRW[bool]`. The ReadWidget for this is an LED, but it would be nice to model the WriteWidget as a pair of buttons marked `start` and `stop`. The resulting screen would be:
```
AcquireTime     |       0.1      | |      0.1      |
Acquire         | start | | stop |        |=|   
```
This could be written as:
```yaml
  - type: SignalRW
    name: Acquire
    pv: Acquire
    widget:
      type: ActionButtons
      buttons:
         start: 1
         stop: 0
    read_pv: Acquire_RBV
    read_widget:
      type: LED
```
So `buttons: Dict[str, Any]`
