### ISSUE TITLE
overly restrictive Schema?

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/pvi#61]
This snippet of device yaml gets a schema error.

The reason is for the _ . The schema only accepts a-z A-Z 0-9. Is there any good reason to omit `-` and `_` from the alowed signal and group names?

```yaml
label: ADGenICam
parent: ADDriver
children:

- type: Group
  name: AVT_Mako_1_52
  layout:
    type: Grid
  children:

  - type: SignalW
    name: GC_GevTimConLatch
    pv: GC_GevTimConLatch
    widget:
      type: TextWrite

  - type: SignalW
    name: GC_GevTimConReset
    pv: GC_GevTimConReset
    widget:
      type: TextWrite
```
